### ISSUE TITLE
Public Repo Checklist

### ISSUE THREAD

**Issue by davidwyld** [GateNLP/gate-teamware#161]
Issue to capture anything that we notice needs doing before we eventually make this repo public.
 - [x] Move GATE specific parameters to a template config/environment variable file, out of `generate-env.sh`
 - [x] Ensure that deployment instructions are generic
 - [x] Make a `main` branch
 - [x] Check that `production` deployment actually works.
 - [x] Look at `new_db_superuser.json`, redesign how new password is set for default superuser of the database.
 - [ ] rename database to `teamware`
 - [x] think about pushing images to a public registry and publishing a Helm chart repository.
   - #183 covers pushing images to `ghcr.io`, which can be made public at the same time as the repo
 - [ ] make `master` the default branch (add branch protections if not already in place)
