### ISSUE TITLE
Search, filtering and sorting of projects, documents and annotation

### ISSUE THREAD

**Issue by twinkarma** [GateNLP/gate-teamware#58]
Basic search and pagination is implemented in #72. Currently on the project page it is searching project name and for documents it's only searching for ID.

After user testing, it'd be good  to specify what properties should be searchable which would be useful to the user. Create a separate widget for each type of search/filter, eg. text field for name and date range for created dates.

* Types of search/filter
  * Project 
    * [ ] id
    * [ ] name
    * [ ] created
    * [ ] user (owner/co-owner) (#264)
    * [ ] Having a My projects and All projects button to easily filter projects, defaults to My projects
  * Document
    * [ ] id
    * [ ] user (uploader? - Currently we don't track this but would it be useful to? especially now that we will have proper project ownership)
    * [ ] created (date)
    * [ ] document type
    * [ ] Content of document
  * Annotation
    * [ ] id
    * [ ] user (annotator)
    * [ ] created (date)
    * [ ] annotation status (completed, pending, etc.)
    * [ ] Content of annotation, e.g. searching for annotations of a given type, eg all of the annotations that are annotated as 'neutral'. 
* Perform actions on document & annotations in combination with the filter
  * [ ] Delete filtered documents (#27)
  * [ ] Delete filtered annotations (#27)
  * [ ] Export filtered documents (#308)

### Searching contents of documents and annotation
Ideally it would be best if we allow the user to search the content of any field inside document and annotation. This should be relatively easy with a simple string field but how best to handle arrays and dictionaries?

**Comment by twinkarma** [comment]
I'm leaning towards supporting search syntax (e.g. similar to google or github search, use `from:2021-01-1` to search for items starting from that date) instead of creating various different UI widgets for filtering different things. 

It would then be possible to string together a relatively complex query like `from:2020-01-01 annotation:label1:neutral -annotation:lable2:positive` to find something from 1st Jan 2020 where label 1 is neutral and label 2 is not positive. 

What does everyone think?
